### ISSUE TITLE
Objects in the air

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#10]

**Comment by recompense-aps** [comment]
Details?

**Comment by Sup3rCondor** [comment]
I was going to comment something here, but I ended up not doing it.

**Comment by Sup3rCondor** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/55172520/66964383-ae503080-f033-11e9-908c-33bc96fe06f7.png)

Example of objects spawning

**Comment by Sup3rCondor** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/55172520/66964414-ccb62c00-f033-11e9-9624-8949b98efe11.png)
![Screenshot (3)](https://user-images.githubusercontent.com/55172520/66964418-d049b300-f033-11e9-8d1f-6f0afa4f56a1.png)
![Screenshot (4)](https://user-images.githubusercontent.com/55172520/66964426-d475d080-f033-11e9-89e9-54cb17401135.png)

These are photos of the series of events which lead to the drop growth and game crashing.
It takes collecting 5-7 drops for this to happen. It occurs on all game levels.

**Comment by recompense-aps** [comment]
Make the obstacles spawn smoothly. Raindrop infinite growth should be fixed as of 0.0.3 (#9 )

**Comment by Sup3rCondor** [comment]
Raindrop growth is fixed.

**Comment by recompense-aps** [comment]
fixed in 0.0.4
