### ISSUE TITLE
0.0.3

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#11]
The game opens but crashes when I try to select which level I want to play on.

**Comment by Sup3rCondor** [comment]
I tried re-downloading but nothing changed.

**Comment by recompense-aps** [comment]
Already know the issue. I'll rebuild and upload it again as 0.0.3

**Comment by Sup3rCondor** [comment]
Going to the side of the screen and pressing 1,2,3 cause the drop to fall and not be stopped by anything.

**Comment by Sup3rCondor** [comment]
Raindrop movement is much better. Is it possible to make the flow more smooth after the press of a key? (Again if that makes sense)

**Comment by Sup3rCondor** [comment]
Objects spawn in onscreen. Sometimes they spawn in right where the drop is going. This could be rage inducing.

**Comment by Sup3rCondor** [comment]
Is it possible to have the cloud cover the entire horizontal level that it occupies?

**Comment by Sup3rCondor** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/55172520/67046660-f2077080-f0ed-11e9-9d59-76a3b9ff760e.png)

Objects are still spawning on top of each other

**Comment by recompense-aps** [comment]
All of this _should_ be fixed as of 0.0.4
