### ISSUE TITLE
Going to the side of the screen and pressing 1,2,3 cause the drop to fall and not be stopped by anything. Maybe consider partial on screen objects?

### ISSUE THREAD

**Issue by recompense-aps** [recompense-aps/Raindrop#14]
Going to the side of the screen and pressing 1,2,3 cause the drop to fall and not be stopped by anything. Maybe consider partial on screen objects?

_Originally posted by @Sup3rCondor in https://github.com/recompense-aps/Raindrop/issues/11#issuecomment-543353026_

**Comment by recompense-aps** [comment]
Can I get a video capture of this?

**Comment by Sup3rCondor** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/55172520/67118285-ca71e000-f1a1-11e9-9feb-57af911a35e4.png)

Here's a picture. The player could even camp out over here and not hit anything. Pressing 2 or 3 just makes it fall faster.

**Comment by recompense-aps** [comment]
fixed in 0.0.4, objects spawn on sides, player can't hide
