### ISSUE TITLE
Movement Style: Raindrop, Snowflake

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#17]
Movement style from build 0.0.4 felt good for raindrop.
Movement in 0.0.5 feels good for snowflake.

**Comment by Sup3rCondor** [comment]
Also, how do you add labels to the issues?

**Comment by recompense-aps** [comment]
> Also, how do you add labels to the issues?

![Capture](https://user-images.githubusercontent.com/49694818/67235856-31430380-f405-11e9-93a9-b0cd96e394da.PNG)

**Comment by recompense-aps** [comment]
> Movement style from build 0.0.4 felt good for raindrop.
> Movement in 0.0.5 feels good for snowflake.

In 0.0.6, see the build notes, you can tweak the values for the speeds of the different drops
