### ISSUE TITLE
Starting drop size

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#19]
Consider the starting drop being a lot smaller. Just bigger than the collectible drops.

**Comment by Sup3rCondor** [comment]
Move speed and distance stay the same

**Comment by recompense-aps** [comment]
@Sup3rCondor I'll add a setting for drop size so you can tweak it to your liking

**Comment by recompense-aps** [comment]
setting is `FreeFall.DropScale` and the default value is 2
