### ISSUE TITLE
I forgot how to do the live thing

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#26]
So i for got how to play the live game through git.

**Comment by Sup3rCondor** [comment]
Sorry

**Comment by recompense-aps** [comment]
![snip1](https://user-images.githubusercontent.com/49694818/68077878-60585e00-fd91-11e9-90fa-25efafd3537a.PNG)

**Comment by recompense-aps** [comment]
fetch in github, then open the project in Godot

**Comment by recompense-aps** [comment]
![Capture](https://user-images.githubusercontent.com/49694818/68077886-7d8d2c80-fd91-11e9-9f51-64927d58f34f.PNG)

**Comment by recompense-aps** [comment]
Then hit the play button

**Comment by Sup3rCondor** [comment]
Thanks
