### ISSUE TITLE
Out of Bounds.

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#35]
Putting raindrop on the side makes it much easier to dodge objects. Could we make the side and out of bounds of sorts. It's either game over, or acts as an object and takes away volume.

**Comment by recompense-aps** [comment]
what about continuing with momentum on the other side? Could be a fun mechanic

**Comment by Sup3rCondor** [comment]
That could work. When you do it have the raindrop go under the black border though if that makes sense.
