### ISSUE TITLE
Stationary objects (0.0.11)

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#43]
Each Level has stationary objects. I will make pictures to demonstrate what I mean.

**Comment by Sup3rCondor** [comment]
![Ocean Objects](https://user-images.githubusercontent.com/55172520/70468938-45aa9080-1a85-11ea-98d5-a609530e7b4b.png)
![Jungle Objects](https://user-images.githubusercontent.com/55172520/70468949-493e1780-1a85-11ea-8cc3-34c9441a0b7a.png)
![City Objects](https://user-images.githubusercontent.com/55172520/70468957-4d6a3500-1a85-11ea-9115-7b22d98d3697.png)

**Comment by Sup3rCondor** [comment]
Obviously, the objects should be centered, I'm not the best at using paint.

**Comment by recompense-aps** [comment]
And do the platforms appear in the same position every time?

**Comment by Sup3rCondor** [comment]
That's what I was thinking. What do you think?

**Comment by recompense-aps** [comment]
I like it

**Comment by recompense-aps** [comment]
Do these platforms hurt you or do you just bounce off them?

**Comment by Sup3rCondor** [comment]
A subtle bounce off of them would make things interesting.
