### ISSUE TITLE
Power Up While Recovering (0.1.0)

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#55]
Collecting the Red power up soon after hitting an object. (The player's drop is still blinking) The drop continues to blink and doesn't change color. The benefits of the power-up do occur in the gameplay though.

**Comment by Sup3rCondor** [comment]
The also happens with the blue power up

**Comment by recompense-aps** [comment]
Recovery now instantly ends when a power up is absorbed
