### ISSUE TITLE
Still Crashing (0.1.2)

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#58]
The game still crashes when I try to go through the portal to the third level.

**Comment by recompense-aps** [comment]
Probably still broken in 0.1.2, but check anyway

**Comment by Sup3rCondor** [comment]
Still Crashes

**Comment by Sup3rCondor** [comment]
![Capture](https://user-images.githubusercontent.com/55172520/71772067-e6b02e00-2f01-11ea-9766-0f54bdef9ed7.PNG)
