### ISSUE TITLE
Scoring

### ISSUE THREAD

**Issue by recompense-aps** [recompense-aps/Raindrop#6]
Make the game score correctly
> Your score is added up by both how many orbs you collect and how many objects you pass

(This score can probably be calculated on the fly, no need to wait until the player fails)

**Comment by recompense-aps** [comment]
This probably needs more design consideration. It scores correctly now, but the formula for score is just:
Score = power ups collected + obstacles passed
What about time? What about hitting an obstacle?

**Comment by Sup3rCondor** [comment]
The idea with how many objects you dodge is a sense of time. Hitting an object will cause your drop to shrink. Let's say you collect X amount of orbs, but when you hit an object it takes away Y from your volume. Once you run out then game ends.

**Comment by Sup3rCondor** [comment]
When you hit an object you could also lose orbs, which would decrease your score.

Or maybe the orbs increase the rate your score grows, and hitting objects decreases your volume, score increase rate, and after you have low enough volume lose the game. (If that makes sense)

**Comment by Sup3rCondor** [comment]
Or the rate at which your score grows is based on your volume. Hitting objects decreases your volume which decreases the rate at which your score increases. What do you think about that?
