### ISSUE TITLE
Power Up Spawning (0.1.2)

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#67]
Make it so that when someone collects a power-up they have to wait for another 15 points till one response? I find that as soon as my current power-up ran out I could just collect another one and be fine. Keep the every ten if the player does not collect a power-up. Is that too much to ask?

**Comment by recompense-aps** [comment]
How it works now:
- powerups spawn when the player scores 15 more points AND 25 seconds have passed since the last powerup was spawned. let me know if you want to tweak those numbers
