### ISSUE TITLE
Game-play Twist? (0.1.2)

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#71]
Going through the portal brought me to the city level again. This only happened one time.

**Comment by recompense-aps** [comment]
This should happen every time you go through the portal on the ocean level. Is that what happened>

**Comment by Sup3rCondor** [comment]
I'll say one in 5 playthroughs When I go through the first portal, I spawn again in the city level, but the desert objects are launched in the air. When I go through the portal again the ocean objects spawn and so forth.

**Comment by recompense-aps** [comment]
should be fixed with #76
