### ISSUE TITLE
Not transitioning to next level, but objects are (0.1.4)

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#78]
I left the game paused for a while. When I returned I died. When I began again when I would go through the portal I would spawn in the city level again, but the objects would be from the desert. When I went through the portal again I stayed in the city, but the objects were ocean objects. I did this for a minute or so and the pattern continued. I'm not sure how to recreate it.

**Comment by recompense-aps** [comment]
Related to #76, should be fixed now
