### ISSUE TITLE
Tutorial Screen Text (0.1.5)

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#80]
Some of the text on the tutorial screen is cut off. Maybe make the text a little bit smaller.
![Tutorial text](https://user-images.githubusercontent.com/55172520/73780944-a6381000-474c-11ea-9178-872eb10e6b87.PNG)

Also there is a dark blue raindrop on the tutorial screen, and we don't have one of those in game.

**Comment by recompense-aps** [comment]
Fixed
