### ISSUE TITLE
Build 0.0.2

### ISSUE THREAD

**Issue by recompense-aps** [recompense-aps/Raindrop#9]
- I know it’s still early, but would it be difficult to have the drop change the direction it looks like it’s going as well when you move it?

- Going to the side of the screen and pressing 1 or 3 will cause you fall at a very fast speed maybe

- Collecting 5 drops causes the drop to expand exponentially and may crash the game

- Game crash around 1700 points with expanded drop issue from up above

- Once the score is over 100 the score count is partially off the screen

**Comment by Sup3rCondor** [comment]
I will be sure to use your fancy website from here forward. I do appreciate you putting the game on google drive.

**Comment by recompense-aps** [comment]
Shouldn't have closed this

**Comment by Sup3rCondor** [comment]
Objects in the air will pawn in at random times. Sometimes they spawn inside the area of another object.

**Comment by recompense-aps** [comment]
![score-issue-snip](https://user-images.githubusercontent.com/49694818/66874692-3584a200-ef69-11e9-89ce-4d0b32fe8803.PNG)

It doesn't crash here, but I'm a little unsure that the problem is completely fixed
